version: '3'
services:
  db:
    container_name: dnd-db
    image: mysql
    environment:
      MYSQL_DATABASE: dnd
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - ./mysqldata:/var/lib/mysql
    restart: always

  server:
    container_name: server
    image: kiseo/dnd-be
    ports:
      - "8080:8080"
    environment:
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      DB_ROOT_USERNAME: ${DB_ROOT_USERNAME}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      DB_NAME: ${DB_NAME}
      SECRET_KEY: ${SECRET_KEY}
      KAKAO_CLIENT_ID: ${KAKAO_CLIENT_ID}
      KAKAO_CLIENT_SECRET: ${KAKAO_CLIENT_SECRET}
      KAKAO_AUTH_URL: ${KAKAO_AUTH_URL}
      KAKAO_API_URL: ${KAKAO_API_URL}
      STORAGE_ACCESS_KEY: ${STORAGE_ACCESS_KEY}
      STORAGE_SECRET_KEY: ${STORAGE_SECRET_KEY}
      STORAGE_BUCKET: ${STORAGE_BUCKET}
      STORAGE_REGION: ${STORAGE_REGION}
      STORAGE_ENDPOINT: ${STORAGE_ENDPOINT}

